[package]
name = "ray-tracing-in-a-weekend"
version = "0.1.0"
authors = ["Thomas Maroulis <thomasmaroulis@gmail.com>"]

[dependencies]
assert_approx_eq = "1.1.0"
itertools = "0.8.0"
rand = "0.6.5"
rayon = "1.0.3"
indicatif = "0.11.0"
console = "0.7.5"
