---
aspect: 2.0
camera:
  look_from:
    x: 0.0
    y: 0.2
    z: 3.0
  look_at:
    x: 0.0
    y: 0.0
    z: -1.0
  view_up:
    x: 0.0
    y: 1.0
    z: 0.0
  vertical_fov: 35.0
  aspect: 2.0
  aperture: 0.1
  focus_distance: 4.0
  time_start: 0.0
  time_end: 1.0
world:
  background:
    top:
      r: 0.5
      g: 0.7
      b: 1.0
    bottom:
      r: 1.0
      g: 1.0
      b: 1.0
  geometries:
    - type: Sphere
      centre:
        x: 0.0
        y: 0.0
        z: -1.0
      radius: 0.5
      material:
        Lambertian:
          albedo:
            r: 0.1
            g: 0.2
            b: 0.5
    - type: Sphere
      centre:
        x: 0.0
        y: -100.5
        z: -1.0
      radius: 100.0
      material:
        Lambertian:
          albedo:
            r: 0.8
            g: 0.8
            b: 0.0
    - type: Sphere
      centre:
        x: 1.0
        y: 0.0
        z: -1.0
      radius: 0.5
      material:
        Metal:
          albedo:
            r: 0.8
            g: 0.6
            b: 0.2
          fuzz: 0.1
    - type: Sphere
      centre:
        x: -1.0
        y: 0.0
        z: -1.0
      radius: -0.45
      material:
        Dielectric:
          refractive_index: 1.5