---
aspect: 1.0
camera:
  look_from:
    x: 278.0
    y: 278.0
    z: -800.0
  look_at:
    x: 278.0
    y: 278.0
    z: 0.0
  view_up:
    x: 0.0
    y: 1.0
    z: 0.0
  vertical_fov: 40.0
  aspect: 1.0
  aperture: 0.0
  focus_distance: 10.0
  time_start: 0.0
  time_end: 1.0
world:
  background:
    top:
      r: 0.0
      g: 0.0
      b: 0.0
    bottom:
      r: 0.0
      g: 0.0
      b: 0.0
  geometries:
    - Flip:
        geometry:
          YzRect:
            y0: 0.0
            y1: 555.0
            z0: 0.0
            z1: 555.0
            k: 555.0
            material:
              Lambertian:
                albedo:
                  Constant:
                    colour:
                      r: 0.12
                      g: 0.45
                      b: 0.15
    - YzRect:
        y0: 0.0
        y1: 555.0
        z0: 0.0
        z1: 555.0
        k: 0.0
        material:
          Lambertian:
            albedo:
              Constant:
                colour:
                  r: 0.65
                  g: 0.05
                  b: 0.05
    - Flip:
        geometry:
          XzRect:
            x0: 213.0
            x1: 343.0
            z0: 227.0
            z1: 332.0
            k: 554.0
            material:
              DiffuseLight:
                emit:
                  Constant:
                    colour:
                      r: 15.0
                      g: 15.0
                      b: 15.0
    - Flip:
        geometry:
          XzRect:
            x0: 0.0
            x1: 555.0
            z0: 0.0
            z1: 555.0
            k: 555.0
            material:
              Lambertian:
                albedo:
                  Constant:
                    colour:
                      r: 0.73
                      g: 0.73
                      b: 0.73
    - XzRect:
        x0: 0.0
        x1: 555.0
        z0: 0.0
        z1: 555.0
        k: 0.0
        material:
          Lambertian:
            albedo:
              Constant:
                colour:
                  r: 0.73
                  g: 0.73
                  b: 0.73
    - Flip:
        geometry:
          XyRect:
            x0: 0.0
            x1: 555.0
            y0: 0.0
            y1: 555.0
            k: 555.0
            material:
              Lambertian:
                albedo:
                  Constant:
                    colour:
                      r: 0.73
                      g: 0.73
                      b: 0.73
    - Sphere:
        centre:
          x: 190.0
          y: 90.0
          z: 190.0
        radius: 90.0
        material:
          Dielectric:
            refractive_index: 1.5
    - Translate:
        geometry:
          RotateY:
            geometry:
              Cube:
                rectangles:
                  - XyRect:
                      x0: 0.0
                      x1: 165.0
                      y0: 0.0
                      y1: 330.0
                      k: 165.0
                      material:
                        Lambertian:
                          albedo:
                            Constant:
                              colour:
                                r: 0.73
                                g: 0.73
                                b: 0.73
                  - Flip:
                      geometry:
                        XyRect:
                          x0: 0.0
                          x1: 165.0
                          y0: 0.0
                          y1: 330.0
                          k: 0.0
                          material:
                            Lambertian:
                              albedo:
                                Constant:
                                  colour:
                                    r: 0.73
                                    g: 0.73
                                    b: 0.73
                  - XzRect:
                      x0: 0.0
                      x1: 165.0
                      z0: 0.0
                      z1: 165.0
                      k: 330.0
                      material:
                        Lambertian:
                          albedo:
                            Constant:
                              colour:
                                r: 0.73
                                g: 0.73
                                b: 0.73
                  - Flip:
                      geometry:
                        XzRect:
                          x0: 0.0
                          x1: 165.0
                          z0: 0.0
                          z1: 165.0
                          k: 0.0
                          material:
                            Lambertian:
                              albedo:
                                Constant:
                                  colour:
                                    r: 0.73
                                    g: 0.73
                                    b: 0.73
                  - YzRect:
                      y0: 0.0
                      y1: 330.0
                      z0: 0.0
                      z1: 165.0
                      k: 165.0
                      material:
                        Lambertian:
                          albedo:
                            Constant:
                              colour:
                                r: 0.73
                                g: 0.73
                                b: 0.73
                  - Flip:
                      geometry:
                        YzRect:
                          y0: 0.0
                          y1: 330.0
                          z0: 0.0
                          z1: 165.0
                          k: 0.0
                          material:
                            Lambertian:
                              albedo:
                                Constant:
                                  colour:
                                    r: 0.73
                                    g: 0.73
                                    b: 0.73
                pmin:
                  x: 0.0
                  y: 0.0
                  z: 0.0
                pmax:
                  x: 165.0
                  y: 330.0
                  z: 165.0
            angle: 15.0
        offset:
          x: 265.0
          y: 0.0
          z: 295.0