---
aspect: 2.0
camera:
  look_from:
    x: 13.0
    y: 2.0
    z: 3.0
  look_at:
    x: 0.0
    y: 0.0
    z: 0.0
  view_up:
    x: 0.0
    y: 1.0
    z: 0.0
  vertical_fov: 20.0
  aspect: 1.5
  aperture: 0.0
  focus_distance: 10.0
  time_start: 0.0
  time_end: 1.0
world:
  background:
    top:
      r: 1.0
      g: 1.0
      b: 1.0
    bottom:
      r: 0.5
      g: 0.7
      b: 1.0
  geometries:
    - type: Sphere
      centre:
        x: 0.0
        y: -10.0
        z: 0.0
      radius: 10.0
      material:
        Lambertian:
          albedo:
            Checker:
              even:
                Constant:
                  colour:
                    r: 0.2
                    g: 0.3
                    b: 0.1
              odd:
                Constant:
                  colour:
                    r: 0.9
                    g: 0.9
                    b: 0.9
    - type: Sphere
      centre:
        x: 0.0
        y: 10.0
        z: 0.0
      radius: 10.0
      material:
        Lambertian:
          albedo:
            Checker:
              even:
                Constant:
                  colour:
                    r: 0.2
                    g: 0.3
                    b: 0.1
              odd:
                Constant:
                  colour:
                    r: 0.9
                    g: 0.9
                    b: 0.9
